- repo: local
  hooks:
  - id: thrift-build
    name: Build the Thrift components
    description: This hook will build the Thrift classes and included them in the commit
    entry: ./bin/thrift-compile.sh
    language: script
    files: \.(thrift)$
    always_run: true
  - id: build-tests
    name: Testing the baa_messages build
    description: This hook will run the tests from the setup.py to check to ame sure that everythign builds correctly
    entry: ./bin/run_tests.sh
    language: script
    files: \.(build-tests)$
    always_run: true
