- repo: local
  hooks:
  - id: thrift-build
    name: Build the Thrift components
    description: This hook will build the Thrift classes and included them in the commit
    entry: ./bin/thrift-compile.sh
    language: script
    files: \.(thrift)$
    always_run: true

