#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None



class Reading:
  """
  Attributes:
   - counts
   - num_channels
   - adc_channel_counts
   - channel_energies
  """

  thrift_spec = (
    None, # 0
    (1, TType.DOUBLE, 'counts', None, None, ), # 1
    (2, TType.I32, 'num_channels', None, None, ), # 2
    (3, TType.MAP, 'adc_channel_counts', (TType.I32,None,TType.I32,None), None, ), # 3
    (4, TType.MAP, 'channel_energies', (TType.DOUBLE,None,TType.DOUBLE,None), None, ), # 4
  )

  def __init__(self, counts=None, num_channels=None, adc_channel_counts=None, channel_energies=None,):
    self.counts = counts
    self.num_channels = num_channels
    self.adc_channel_counts = adc_channel_counts
    self.channel_energies = channel_energies

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.DOUBLE:
          self.counts = iprot.readDouble()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.num_channels = iprot.readI32()
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.MAP:
          self.adc_channel_counts = {}
          (_ktype1, _vtype2, _size0 ) = iprot.readMapBegin()
          for _i4 in xrange(_size0):
            _key5 = iprot.readI32()
            _val6 = iprot.readI32()
            self.adc_channel_counts[_key5] = _val6
          iprot.readMapEnd()
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.MAP:
          self.channel_energies = {}
          (_ktype8, _vtype9, _size7 ) = iprot.readMapBegin()
          for _i11 in xrange(_size7):
            _key12 = iprot.readDouble()
            _val13 = iprot.readDouble()
            self.channel_energies[_key12] = _val13
          iprot.readMapEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('Reading')
    if self.counts is not None:
      oprot.writeFieldBegin('counts', TType.DOUBLE, 1)
      oprot.writeDouble(self.counts)
      oprot.writeFieldEnd()
    if self.num_channels is not None:
      oprot.writeFieldBegin('num_channels', TType.I32, 2)
      oprot.writeI32(self.num_channels)
      oprot.writeFieldEnd()
    if self.adc_channel_counts is not None:
      oprot.writeFieldBegin('adc_channel_counts', TType.MAP, 3)
      oprot.writeMapBegin(TType.I32, TType.I32, len(self.adc_channel_counts))
      for kiter14,viter15 in self.adc_channel_counts.items():
        oprot.writeI32(kiter14)
        oprot.writeI32(viter15)
      oprot.writeMapEnd()
      oprot.writeFieldEnd()
    if self.channel_energies is not None:
      oprot.writeFieldBegin('channel_energies', TType.MAP, 4)
      oprot.writeMapBegin(TType.DOUBLE, TType.DOUBLE, len(self.channel_energies))
      for kiter16,viter17 in self.channel_energies.items():
        oprot.writeDouble(kiter16)
        oprot.writeDouble(viter17)
      oprot.writeMapEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.counts is None:
      raise TProtocol.TProtocolException(message='Required field counts is unset!')
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.counts)
    value = (value * 31) ^ hash(self.num_channels)
    value = (value * 31) ^ hash(self.adc_channel_counts)
    value = (value * 31) ^ hash(self.channel_energies)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class Setting:
  """
  Attributes:
   - sample_frequency
   - voltage
  """

  thrift_spec = (
    None, # 0
    (1, TType.DOUBLE, 'sample_frequency', None, None, ), # 1
    (2, TType.DOUBLE, 'voltage', None, None, ), # 2
  )

  def __init__(self, sample_frequency=None, voltage=None,):
    self.sample_frequency = sample_frequency
    self.voltage = voltage

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.DOUBLE:
          self.sample_frequency = iprot.readDouble()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.DOUBLE:
          self.voltage = iprot.readDouble()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('Setting')
    if self.sample_frequency is not None:
      oprot.writeFieldBegin('sample_frequency', TType.DOUBLE, 1)
      oprot.writeDouble(self.sample_frequency)
      oprot.writeFieldEnd()
    if self.voltage is not None:
      oprot.writeFieldBegin('voltage', TType.DOUBLE, 2)
      oprot.writeDouble(self.voltage)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.sample_frequency)
    value = (value * 31) ^ hash(self.voltage)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
