#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None



class BAAMessage:
  """
  Attributes:
   - sender_id
   - message_time
   - payload_class
   - payload
   - receiver_id
   - gps_coordinates
   - sensor_id
   - sensor_unit_id
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'sender_id', None, None, ), # 1
    (2, TType.DOUBLE, 'message_time', None, None, ), # 2
    (3, TType.STRING, 'payload_class', None, None, ), # 3
    (4, TType.STRING, 'payload', None, None, ), # 4
    (5, TType.STRING, 'receiver_id', None, None, ), # 5
    (6, TType.LIST, 'gps_coordinates', (TType.DOUBLE,None), None, ), # 6
    (7, TType.I32, 'sensor_id', None, None, ), # 7
    (8, TType.I32, 'sensor_unit_id', None, None, ), # 8
  )

  def __init__(self, sender_id=None, message_time=None, payload_class=None, payload=None, receiver_id=None, gps_coordinates=None, sensor_id=None, sensor_unit_id=None,):
    self.sender_id = sender_id
    self.message_time = message_time
    self.payload_class = payload_class
    self.payload = payload
    self.receiver_id = receiver_id
    self.gps_coordinates = gps_coordinates
    self.sensor_id = sensor_id
    self.sensor_unit_id = sensor_unit_id

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.sender_id = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.DOUBLE:
          self.message_time = iprot.readDouble()
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.payload_class = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRING:
          self.payload = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.STRING:
          self.receiver_id = iprot.readString()
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.LIST:
          self.gps_coordinates = []
          (_etype3, _size0) = iprot.readListBegin()
          for _i4 in xrange(_size0):
            _elem5 = iprot.readDouble()
            self.gps_coordinates.append(_elem5)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.I32:
          self.sensor_id = iprot.readI32()
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.I32:
          self.sensor_unit_id = iprot.readI32()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('BAAMessage')
    if self.sender_id is not None:
      oprot.writeFieldBegin('sender_id', TType.STRING, 1)
      oprot.writeString(self.sender_id)
      oprot.writeFieldEnd()
    if self.message_time is not None:
      oprot.writeFieldBegin('message_time', TType.DOUBLE, 2)
      oprot.writeDouble(self.message_time)
      oprot.writeFieldEnd()
    if self.payload_class is not None:
      oprot.writeFieldBegin('payload_class', TType.STRING, 3)
      oprot.writeString(self.payload_class)
      oprot.writeFieldEnd()
    if self.payload is not None:
      oprot.writeFieldBegin('payload', TType.STRING, 4)
      oprot.writeString(self.payload)
      oprot.writeFieldEnd()
    if self.receiver_id is not None:
      oprot.writeFieldBegin('receiver_id', TType.STRING, 5)
      oprot.writeString(self.receiver_id)
      oprot.writeFieldEnd()
    if self.gps_coordinates is not None:
      oprot.writeFieldBegin('gps_coordinates', TType.LIST, 6)
      oprot.writeListBegin(TType.DOUBLE, len(self.gps_coordinates))
      for iter6 in self.gps_coordinates:
        oprot.writeDouble(iter6)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.sensor_id is not None:
      oprot.writeFieldBegin('sensor_id', TType.I32, 7)
      oprot.writeI32(self.sensor_id)
      oprot.writeFieldEnd()
    if self.sensor_unit_id is not None:
      oprot.writeFieldBegin('sensor_unit_id', TType.I32, 8)
      oprot.writeI32(self.sensor_unit_id)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.sender_id is None:
      raise TProtocol.TProtocolException(message='Required field sender_id is unset!')
    if self.message_time is None:
      raise TProtocol.TProtocolException(message='Required field message_time is unset!')
    if self.payload_class is None:
      raise TProtocol.TProtocolException(message='Required field payload_class is unset!')
    if self.payload is None:
      raise TProtocol.TProtocolException(message='Required field payload is unset!')
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.sender_id)
    value = (value * 31) ^ hash(self.message_time)
    value = (value * 31) ^ hash(self.payload_class)
    value = (value * 31) ^ hash(self.payload)
    value = (value * 31) ^ hash(self.receiver_id)
    value = (value * 31) ^ hash(self.gps_coordinates)
    value = (value * 31) ^ hash(self.sensor_id)
    value = (value * 31) ^ hash(self.sensor_unit_id)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
